/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblio;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.Font;
import java.awt.Color;
import java.awt.Font;
   import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;



/**
 *
 * @author CLOVIS
 */

public class AccueilUser extends javax.swing.JFrame {

    private JTextField txtNomins = new JTextField(); // Champ pour le Nom
    private JTextField txtPrenomins = new JTextField(); // Champ pour le Prénom
    private JTextField txtEmailins = new JTextField(); // Champ pour l'Email
    private JTextField txtTelephone = new JTextField(); // Champ pour l'Email

     private JDesktopPane jDesktopPane;

    /**
     * Creates new form AccueilUser
     */


        String nomUser, prenomUser, emailUser;
  private String nom;
private String prenom;
private String email;


public AccueilUser(String nom, String prenom, String email) {
    initComponents();
 
    ThemeManager.appliquerTheme(getContentPane());

        this.nomUser = nom;
    this.prenomUser = prenom;
    this.emailUser = email;
         setLocationRelativeTo(null); // Centre la fenêtre

     this.setContentPane(jPanel1); // Définit le DesktopPane comme contenu principal
         
         

// Récupérer la date et l'heure actuelles
LocalDateTime maintenant = LocalDateTime.now();


// Formater la date séparément
DateTimeFormatter formatDate = DateTimeFormatter.ofPattern("dd/MM/yyyy");
String date = maintenant.format(formatDate);
// Formater l'heure séparément
DateTimeFormatter formatHeure = DateTimeFormatter.ofPattern("HH:mm:ss");
String heure = maintenant.format(formatHeure);

// Mettre à jour le texte du JLabel avec le nom, prénom, date et heure
txtconnecter.setText("Connecté en tant que : " + nom + " " + prenom

    + "   " + "Le : " + date 
    + "   " + "À : " + heure);


// Mettre le texte en blanc
txtconnecter.setForeground(Color.WHITE);

// Le rendre gras et plus grand
txtconnecter.setFont(new Font("Arial", Font.BOLD, 14));

// Ajouter une icône (assure-toi que l'icône existe au bon chemin)
txtconnecter.setIcon(new ImageIcon(getClass().getResource("/icon/ordi.png")));

// Ajuster l'alignement de l'icône et du texte
txtconnecter.setHorizontalTextPosition(SwingConstants.RIGHT);
txtconnecter.setVerticalTextPosition(SwingConstants.CENTER);






    setLocationRelativeTo(null); // Centre la fenêtre sur l'écran

}

             
 


    public AccueilUser(){
        
        // Initialise les variables globales dans le constructeur
        txtNomins = new JTextField(); // Initialise txtNomins
        txtPrenomins = new JTextField(); // Initialise txtPrenomins
        txtEmailins = new JTextField(); // Initialise txtEmailins
          

        initComponents();

       

         JPanel jPanel1 = new JPanel(); // Crée un panneau
    jPanel1.setLayout(new java.awt.FlowLayout()); // Utilise un FlowLayout
     setLocationRelativeTo(null); // Centre la fenêtre 
      img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AccueilBilio.png")));
      btnGererProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Profil.png")));
      btnRechercherDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Recherche.png")));
      btnSeDeconnecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deconn.png")));
      btnSeDeconnecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deconn.png")));
       txtconnecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ordi.png")));

         // Crée le JLabel et configure-le
         
        txtconnecter = new JLabel();
        txtconnecter.setBounds(20, 20, 250, 30);
       
        txtconnecter.setIcon(new ImageIcon(getClass().getResource("/icon/ordi.png")));
        this.add(txtconnecter);

        this.setLayout(null);
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        
        
        
ThemeManager.appliquerTheme(getContentPane());



    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGererProfil = new javax.swing.JButton();
        btnRechercherDoc = new javax.swing.JButton();
        btnSeDeconnecter = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        txtconnecter = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        txtPref = new javax.swing.JMenuItem();
        txtAid = new javax.swing.JMenuItem();
        txtProp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        btnGererProfil.setBackground(new java.awt.Color(0, 102, 102));
        btnGererProfil.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnGererProfil.setForeground(new java.awt.Color(255, 255, 255));
        btnGererProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Profil.png"))); // NOI18N
        btnGererProfil.setText("Gerer Votre Profil");
        btnGererProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGererProfilActionPerformed(evt);
            }
        });

        btnRechercherDoc.setBackground(new java.awt.Color(0, 102, 102));
        btnRechercherDoc.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnRechercherDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnRechercherDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Recherche.png"))); // NOI18N
        btnRechercherDoc.setText("Rechercher un Document");
        btnRechercherDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherDocActionPerformed(evt);
            }
        });

        btnSeDeconnecter.setBackground(new java.awt.Color(0, 102, 102));
        btnSeDeconnecter.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnSeDeconnecter.setForeground(new java.awt.Color(255, 255, 255));
        btnSeDeconnecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deconn.png"))); // NOI18N
        btnSeDeconnecter.setText("Se déconnecter");
        btnSeDeconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeDeconnecterActionPerformed(evt);
            }
        });

        img.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        img.setForeground(new java.awt.Color(255, 181, 54));
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AccueilBilio.png"))); // NOI18N
        img.setText("Bienvenue dans Votre Zone Accueil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnGererProfil)
                        .addGap(95, 95, 95)
                        .addComponent(btnRechercherDoc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnSeDeconnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtconnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtconnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGererProfil)
                    .addComponent(btnRechercherDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addComponent(btnSeDeconnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file.png"))); // NOI18N
        jMenu1.setLabel("Gestion");

        txtPref.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/preferences.png"))); // NOI18N
        txtPref.setText("Préférences");
        txtPref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrefActionPerformed(evt);
            }
        });
        jMenu1.add(txtPref);

        txtAid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/aide.png"))); // NOI18N
        txtAid.setText("Aide");
        txtAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAidActionPerformed(evt);
            }
        });
        jMenu1.add(txtAid);

        txtProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/propos.png"))); // NOI18N
        txtProp.setText("À Propos");
        txtProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPropActionPerformed(evt);
            }
        });
        jMenu1.add(txtProp);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGererProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGererProfilActionPerformed
        // TODO add your handling code here
             // Récupère les infos depuis les variables globales ou passées
     String nom = txtNomins.getText();
     String prenom = txtPrenomins.getText();
     String email = txtEmailins.getText();

    // Ouvre la fenêtre ProfilUser en lui passant les infos
    ProfilUser profil = new ProfilUser(nomUser, prenomUser, emailUser);
    profil.setVisible(true);
    
    // Optionnel : fermer AccueilUser
    this.dispose();

    }//GEN-LAST:event_btnGererProfilActionPerformed

    private void btnSeDeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeDeconnecterActionPerformed
        // TODO add your handling code here:
     int choix = JOptionPane.showOptionDialog(
    null,
    "Voulez-vous vraiment vous déconnecter ?",
    "Confirmation",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,
    new Object[]{"Oui", "Non"},
    "Oui"
);

if (choix == 0) { // 0 correspond à "Oui"
    new formulaire().setVisible(true); // retourne au formulaire d’authentification
    this.dispose(); // ferme AccueilUser
}

   


    }//GEN-LAST:event_btnSeDeconnecterActionPerformed

    private void btnRechercherDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherDocActionPerformed
        // TODO add your handling code here:
 
         // Crée une instance de l'internal frame "Rechercher"
    Rechercher rechercherFrame = new Rechercher();

    // Ajoute l'internal frame au jDesktopPane
    jPanel1.add(rechercherFrame);

    // (Optionnel) Centre l'internal frame dans le jDesktopPane
    rechercherFrame.setLocation(
         (jPanel1.getWidth() - rechercherFrame.getWidth()) / 2,
         (jPanel1.getHeight() - rechercherFrame.getHeight()) / 2
    );

    // Rends l'internal frame visible
    rechercherFrame.setVisible(true);

    // (Optionnel) Met l'internal frame au premier plan et le sélectionne
    try {
        rechercherFrame.setSelected(true);
    } catch (java.beans.PropertyVetoException ex) {
        ex.printStackTrace();
    }

    }//GEN-LAST:event_btnRechercherDocActionPerformed

    private void txtPrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrefActionPerformed
        // TODO add your handling code here:
          PreferenceFrame pref = new PreferenceFrame();
    jPanel1.add(pref);
    pref.setVisible(true);
    }//GEN-LAST:event_txtPrefActionPerformed

    private void txtAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAidActionPerformed
        // TODO add your handling code here:
         AideFrame aide = new AideFrame();
    jPanel1.add(aide);
    aide.setVisible(true);
    }//GEN-LAST:event_txtAidActionPerformed

    private void txtPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPropActionPerformed
        // TODO add your handling code here:
         ProposFrame propos = new ProposFrame();
    jPanel1.add(propos);
    propos.setVisible(true);
    }//GEN-LAST:event_txtPropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  new AccueilUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGererProfil;
    private javax.swing.JButton btnRechercherDoc;
    private javax.swing.JButton btnSeDeconnecter;
    private javax.swing.JLabel img;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem txtAid;
    private javax.swing.JMenuItem txtPref;
    private javax.swing.JMenuItem txtProp;
    private javax.swing.JLabel txtconnecter;
    // End of variables declaration//GEN-END:variables
}
