package biblio;
import javax.swing.*;
import biblio.Accueil;
import biblio.Rechercher;
import biblio.inscription;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author CLOVIS
 */
public class Accueil extends javax.swing.JFrame {
   private JInternalFrame currentFrame;

        private JFrame frame;
        private JDesktopPane desktopPane = new JDesktopPane();

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        
        initComponents(); 
       setLocationRelativeTo(null); // Centre la fenêtre
          ThemeManager.appliquerTheme(this.getContentPane());

       

    this.setContentPane(jDesktopPane); // Définit le DesktopPane comme contenu principal
    setVisible(true); // Rend visible

}




    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        deconnecterbtn = new javax.swing.JButton();
        quitterbtn = new javax.swing.JButton();
        buttonaccueilrech = new javax.swing.JButton();
        zoneimg = new javax.swing.JLabel();
        Menubar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        txtPreference = new javax.swing.JMenuItem();
        menuAide = new javax.swing.JMenuItem();
        txtApropos = new javax.swing.JMenuItem();
        gererempreint = new javax.swing.JMenu();
        nouvelempreint = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGestionLivre = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuGestionUtilisateur = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane.setBackground(new java.awt.Color(0, 102, 102));
        jDesktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 181, 54));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bibliogestio.png"))); // NOI18N
        jLabel2.setText("Gestion de Bibliothèque");

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        deconnecterbtn.setBackground(new java.awt.Color(0, 102, 102));
        deconnecterbtn.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        deconnecterbtn.setForeground(new java.awt.Color(255, 255, 255));
        deconnecterbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deconnecter.png"))); // NOI18N
        deconnecterbtn.setText("Se déconnecter");
        deconnecterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnecterbtnActionPerformed(evt);
            }
        });

        quitterbtn.setBackground(new java.awt.Color(0, 102, 102));
        quitterbtn.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        quitterbtn.setForeground(new java.awt.Color(255, 255, 255));
        quitterbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/log-out_10067715.png"))); // NOI18N
        quitterbtn.setText("Quitter");
        quitterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterbtnActionPerformed(evt);
            }
        });

        buttonaccueilrech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/recherch.png"))); // NOI18N
        buttonaccueilrech.setText("Rechercher un livre");
        buttonaccueilrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonaccueilrechActionPerformed(evt);
            }
        });

        zoneimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Biblioimg.png"))); // NOI18N

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(buttonaccueilrech, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                .addComponent(zoneimg, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(deconnecterbtn)
                        .addGap(92, 92, 92)
                        .addComponent(quitterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jDesktopPane1))
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonaccueilrech, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(zoneimg, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitterbtn)
                    .addComponent(deconnecterbtn))
                .addGap(0, 59, Short.MAX_VALUE))
        );

        Menubar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        file.setBackground(new java.awt.Color(0, 153, 153));
        file.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file.png"))); // NOI18N
        file.setText("File");

        txtPreference.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/preferences.png"))); // NOI18N
        txtPreference.setText("Préférences");
        txtPreference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreferenceActionPerformed(evt);
            }
        });
        file.add(txtPreference);

        menuAide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/aide.png"))); // NOI18N
        menuAide.setText("Aide");
        menuAide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAideActionPerformed(evt);
            }
        });
        file.add(menuAide);

        txtApropos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/propos.png"))); // NOI18N
        txtApropos.setText("À Propos");
        txtApropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAproposActionPerformed(evt);
            }
        });
        file.add(txtApropos);

        Menubar.add(file);

        gererempreint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/emprunt.png"))); // NOI18N
        gererempreint.setText("Gerer les Emprunts");

        nouvelempreint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/retour.png"))); // NOI18N
        nouvelempreint.setText("Emprunt/Restitution");
        nouvelempreint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouvelempreintActionPerformed(evt);
            }
        });
        gererempreint.add(nouvelempreint);

        Menubar.add(gererempreint);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/livre.png"))); // NOI18N
        jMenu2.setText("Gestion Livres");

        menuGestionLivre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/newEmpreint.png"))); // NOI18N
        menuGestionLivre.setText("Menu Gestion Livre");
        menuGestionLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionLivreActionPerformed(evt);
            }
        });
        jMenu2.add(menuGestionLivre);

        Menubar.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/utilisat.png"))); // NOI18N
        jMenu1.setText("Gestion Utilisateurs");

        menuGestionUtilisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/auteur.png"))); // NOI18N
        menuGestionUtilisateur.setText("Menu Gestion des Utilisateurs");
        menuGestionUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionUtilisateurActionPerformed(evt);
            }
        });
        jMenu1.add(menuGestionUtilisateur);

        Menubar.add(jMenu1);

        setJMenuBar(Menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonaccueilrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonaccueilrechActionPerformed
        // TODO add your handling code here:
   
        // Crée une instance de l'internal frame "Rechercher"
    Rechercher rechercherFrame = new Rechercher();

    // Ajoute l'internal frame au jDesktopPane
    jDesktopPane.add(rechercherFrame);

    // (Optionnel) Centre l'internal frame dans le jDesktopPane
    rechercherFrame.setLocation(
         (jDesktopPane.getWidth() - rechercherFrame.getWidth()) / 2,
         (jDesktopPane.getHeight() - rechercherFrame.getHeight()) / 2
    );

    // Rends l'internal frame visible
    rechercherFrame.setVisible(true);

    // (Optionnel) Met l'internal frame au premier plan et le sélectionne
    try {
        rechercherFrame.setSelected(true);
    } catch (java.beans.PropertyVetoException ex) {
        ex.printStackTrace();
    }


    }//GEN-LAST:event_buttonaccueilrechActionPerformed

    private void deconnecterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnecterbtnActionPerformed
        // TODO add your handling code here:
          int choix = JOptionPane.showOptionDialog(
    null,
    "Voulez-vous vraiment vous déconnecter ?",
    "Confirmation",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,
    new Object[]{"Oui", "Non"},
    "Oui"
);

if (choix == 0) { // 0 correspond à "Oui"
    new formulaire().setVisible(true); // retourne au formulaire d’authentification
    this.dispose(); // ferme AccueilUser
}

if (currentFrame != null) {
    currentFrame.dispose();
}
currentFrame = new JInternalGestionUtilisateur();
desktopPane.add(currentFrame);
currentFrame.setVisible(true);

    }//GEN-LAST:event_deconnecterbtnActionPerformed

    private void quitterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterbtnActionPerformed
        // TODO add your handling code here:
            // Message de confirmation avant de quitter
     int choix = JOptionPane.showOptionDialog(
    null,
    "Voulez-vous vraiment quitter ?",
    "Quitter",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,
    new Object[]{"Oui", "Non"},
    "Oui"
);
    if (choix == 0) {
        System.exit(0); // Ferme l'application
    }
    
if (currentFrame != null) {
    currentFrame.dispose();
}
currentFrame = new JInternalGestionUtilisateur();
desktopPane.add(currentFrame);
currentFrame.setVisible(true);


    }//GEN-LAST:event_quitterbtnActionPerformed

    private void nouvelempreintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouvelempreintActionPerformed
        // TODO add your handling code here:
        EmpruntForm ef = new EmpruntForm();
        jDesktopPane.add(ef);
        ef.setVisible(true);
    }//GEN-LAST:event_nouvelempreintActionPerformed

    private void menuGestionLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionLivreActionPerformed
        // Création de la fenêtre interne
        JInternalGestionLivre gestionLivre = new JInternalGestionLivre();
        jDesktopPane.add(gestionLivre); // 🔁 remplace par le vrai nom du JDesktopPane
        gestionLivre.setVisible(true);
    }//GEN-LAST:event_menuGestionLivreActionPerformed

    private void menuGestionUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionUtilisateurActionPerformed
        // TODO add your handling code here:
        JInternalGestionUtilisateur gestionUtilisateur = new JInternalGestionUtilisateur(); // Instancie Gestion Utilisateur
        jDesktopPane.add(gestionUtilisateur); // Ajoute au DesktopPane
        gestionUtilisateur.setVisible(true); // Rend visible

        gestionUtilisateur.setLocation(
            (jDesktopPane.getWidth() - gestionUtilisateur.getWidth()) / 2,
            (jDesktopPane.getHeight() - gestionUtilisateur.getHeight()) / 2
        );

        try {
            gestionUtilisateur.setSelected(true); // Mets au premier plan
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace(); // Gère une erreur éventuelle
        }
    }//GEN-LAST:event_menuGestionUtilisateurActionPerformed

    private void txtPreferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreferenceActionPerformed
        // TODO add your handling code here:
         PreferenceFrame pref = new PreferenceFrame();
    jDesktopPane.add(pref);
    pref.setVisible(true);

    }//GEN-LAST:event_txtPreferenceActionPerformed

    private void txtAproposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAproposActionPerformed
        // TODO add your handling code here:
     ProposFrame propos = new ProposFrame();
    jDesktopPane.add(propos);
    propos.setVisible(true);
    }//GEN-LAST:event_txtAproposActionPerformed

    private void menuAideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAideActionPerformed
        // TODO add your handling code here:
           AideFrame aide = new AideFrame();
    jDesktopPane.add(aide);
    aide.setVisible(true);
    
    }//GEN-LAST:event_menuAideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menubar;
    private javax.swing.JButton buttonaccueilrech;
    private javax.swing.JButton deconnecterbtn;
    private javax.swing.JMenu file;
    private javax.swing.JMenu gererempreint;
    private javax.swing.JPanel jDesktopPane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem menuAide;
    private javax.swing.JMenuItem menuGestionLivre;
    private javax.swing.JMenuItem menuGestionUtilisateur;
    private javax.swing.JMenuItem nouvelempreint;
    private javax.swing.JButton quitterbtn;
    private javax.swing.JMenuItem txtApropos;
    private javax.swing.JMenuItem txtPreference;
    private javax.swing.JLabel zoneimg;
    // End of variables declaration//GEN-END:variables
}
