/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblio;

import javax.swing.JOptionPane;
import javax.swing.*;
import biblio.Accueil;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;


/**
 *
 * @author CLOVIS
 */
public class inscription extends javax.swing.JFrame {

    /**
     * Creates new form inscription
     */
    public inscription() {
        initComponents();
        inscrip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/inscription.png")));
        setLocationRelativeTo(null); // Centre la fenêtre
        
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameinscrip = new javax.swing.JLabel();
        txtNomins = new javax.swing.JTextField();
        emailinscrip = new javax.swing.JLabel();
        motdepasseinscript = new javax.swing.JLabel();
        txtEmailins = new javax.swing.JTextField();
        txtMotDePasseins = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        motdepasseinscriptconfirmation = new javax.swing.JLabel();
        txtConfirmerMotDePasseins = new javax.swing.JPasswordField();
        btnValider = new javax.swing.JButton();
        inscrip = new javax.swing.JLabel();
        prenominscription = new javax.swing.JLabel();
        txtPrenomins = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        nameinscrip.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        nameinscrip.setForeground(new java.awt.Color(255, 255, 255));
        nameinscrip.setText("NOM");

        emailinscrip.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N
        emailinscrip.setForeground(new java.awt.Color(255, 255, 255));
        emailinscrip.setText("Email");

        motdepasseinscript.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N
        motdepasseinscript.setForeground(new java.awt.Color(255, 255, 255));
        motdepasseinscript.setText("Mot de Passe");

        txtMotDePasseins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotDePasseinsActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(242, 192, 103));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        motdepasseinscriptconfirmation.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N
        motdepasseinscriptconfirmation.setForeground(new java.awt.Color(255, 255, 255));
        motdepasseinscriptconfirmation.setText("Confirmer Mot de Passe");

        txtConfirmerMotDePasseins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmerMotDePasseinsActionPerformed(evt);
            }
        });

        btnValider.setBackground(new java.awt.Color(0, 102, 102));
        btnValider.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnValider.setForeground(new java.awt.Color(255, 181, 54));
        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        inscrip.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        inscrip.setForeground(new java.awt.Color(255, 181, 54));
        inscrip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/inscription.png"))); // NOI18N
        inscrip.setText("Inscription à votre espace User");

        prenominscription.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N
        prenominscription.setForeground(new java.awt.Color(255, 255, 255));
        prenominscription.setText("Prénom");

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Telephone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailinscrip, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prenominscription, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameinscrip, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(motdepasseinscript, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(motdepasseinscriptconfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailins, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(txtConfirmerMotDePasseins, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrenomins)
                            .addComponent(txtNomins)
                            .addComponent(txtTelephone))
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(inscrip, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(txtMotDePasseins, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(inscrip, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameinscrip)
                    .addComponent(txtNomins, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrenomins, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenominscription))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailinscrip)
                    .addComponent(txtEmailins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTelephone)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMotDePasseins, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motdepasseinscript))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motdepasseinscriptconfirmation)
                    .addComponent(txtConfirmerMotDePasseins, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfirmerMotDePasseinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmerMotDePasseinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmerMotDePasseinsActionPerformed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        // TODO add your handling code here:
        
        btnValider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

   String nom = txtNomins.getText();
   String prenom = txtPrenomins.getText();
   String email = txtEmailins.getText();
   String telephone = txtTelephone.getText();
   String motdepasse = new String(txtMotDePasseins.getPassword());
   String confirmMotdepasse = new String(txtConfirmerMotDePasseins.getPassword());

if (nom.isEmpty() || prenom.isEmpty() || email.isEmpty() || telephone.isEmpty() || motdepasse.isEmpty() || confirmMotdepasse.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Tous les champs doivent être remplis.");
    return; // Arrête l'exécution si un champ est vide
}

if (!email.matches("^[a-z0-9._-]+@[a-z0-9.-]+\\.[a-z]{2,}$")) {
    JOptionPane.showMessageDialog(this, "Veuillez entrer une adresse email valide.");
    return;
}


if (!motdepasse.equals(confirmMotdepasse)) {
    JOptionPane.showMessageDialog(this, "Les mots de passe ne correspondent pas.");
return;
} else {
    JOptionPane.showMessageDialog(this, "Inscription réussie ! Bienvenue " + nom + " " + prenom);
   
}  
  
      
      
     nom = txtNomins.getText();
     prenom = txtPrenomins.getText();
     email = txtEmailins.getText();

    // Tu peux afficher un message de confirmation
   

    // Ensuite tu ouvres AccueilUser avec les données
    AccueilUser accueil = new AccueilUser(nom, prenom, email);
    accueil.setVisible(true);
    this.dispose(); // Ferme la page inscription
    
     try (Connection conn = DBConnexion.getConnection();
         PreparedStatement stmt = conn.prepareStatement(
             "INSERT INTO utilisateurs (nom, prenom, email, telephone, mot_de_passe) VALUES (?, ?, ?, ?, ?)")) {

        stmt.setString(1, nom);
        stmt.setString(2, prenom);
        stmt.setString(3, email);
        stmt.setString(4, telephone);
        String motdepasseHashe = PasswordUtils.hashPassword(motdepasse);
        stmt.setString(5, motdepasseHashe);

        
        stmt.executeUpdate(); // Insère les données dans la base
        JOptionPane.showMessageDialog(this, "Inscription réussie ! Bienvenue " + nom + " " + prenom);

        
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors de l'inscription : " + ex.getMessage());
    }

    

      
    }//GEN-LAST:event_btnValiderActionPerformed

    private void txtMotDePasseinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotDePasseinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotDePasseinsActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel emailinscrip;
    private javax.swing.JLabel inscrip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel motdepasseinscript;
    private javax.swing.JLabel motdepasseinscriptconfirmation;
    private javax.swing.JLabel nameinscrip;
    private javax.swing.JLabel prenominscription;
    private javax.swing.JPasswordField txtConfirmerMotDePasseins;
    private javax.swing.JTextField txtEmailins;
    private javax.swing.JPasswordField txtMotDePasseins;
    private javax.swing.JTextField txtNomins;
    private javax.swing.JTextField txtPrenomins;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
