/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblio;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 *
 * @author CLOVIS
 */
public class ProfilUser extends javax.swing.JFrame {
     
    private JTextField txtNomins;
    private JTextField txtPrenomins;
    private JTextField txtEmailins;
    private String nom;
    private String prenom;
    private String email;


    /**
     * Creates new form ProfilUser
     */
    public ProfilUser(String nom, String prenom, String email) {
        initComponents();
        
    this.nom = nom;
    this.prenom = prenom;
    this.email = email;
    txtNompro.setText(nom);
    txtPrenompro.setText(prenom);
    txtEmailpro.setText(email);
        
        JLabel lblMessage = new JLabel("Bienvenue dans la gestion de votre profil !");
        lblMessage.setBounds(50, 50, 300, 30);
        add(lblMessage);
        setLocationRelativeTo(null); // Centre la fenêtre sur l'écran
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png")));
   
                  ThemeManager.appliquerTheme(this.getContentPane());

        


    }
 

public String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hashedBytes = md.digest(password.getBytes()); // Hashage du mot de passe
        StringBuilder sb = new StringBuilder();
        for (byte b : hashedBytes) {
            sb.append(String.format("%02x", b)); // Conversion des octets en hexadécimal
        }
        return sb.toString();
    } catch (NoSuchAlgorithmException e) {
        throw new RuntimeException("Erreur : Algorithme SHA-256 introuvable", e);
    }
}

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNompro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrenompro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmailpro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAncienMotDePasse = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtNouveauMotDePasse = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtConfirmmerMotDePasse = new javax.swing.JPasswordField();
        btnChangerMotDePasse = new javax.swing.JButton();
        btnRetourAccueil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        profil.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        profil.setForeground(new java.awt.Color(255, 181, 54));
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N
        profil.setText("Benvenue sur votre Profil");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prénom");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        txtEmailpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailproActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ancien Mot de Passe");

        txtAncienMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAncienMotDePasseActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nouveau Mot de Passe");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirmer Mot de Passe");

        btnChangerMotDePasse.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnChangerMotDePasse.setText("Changer le Mot de Passe");
        btnChangerMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangerMotDePasseActionPerformed(evt);
            }
        });

        btnRetourAccueil.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnRetourAccueil.setText("Retour Accueil");
        btnRetourAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourAccueilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNompro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrenompro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailpro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAncienMotDePasse, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtNouveauMotDePasse)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConfirmmerMotDePasse)))
                .addGap(259, 259, 259))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(profil))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnChangerMotDePasse)
                        .addGap(34, 34, 34)
                        .addComponent(btnRetourAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profil, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNompro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAncienMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailpro, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(txtNouveauMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrenompro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtConfirmmerMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetourAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangerMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(220, 220, 220))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangerMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangerMotDePasseActionPerformed
        // TODO add your handling code here:
 
    try {
        // Récupération des valeurs des champs
        String ancienMotDePasse = new String(txtAncienMotDePasse.getPassword());
        String nouveauMotDePasse = new String(txtNouveauMotDePasse.getPassword());
        String confirmerMotDePasse = new String(txtConfirmmerMotDePasse.getPassword());

        // Vérifie que tous les champs sont remplis
        if (ancienMotDePasse.trim().isEmpty() || nouveauMotDePasse.trim().isEmpty() || confirmerMotDePasse.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tous les champs doivent être remplis !");
            return;
        }

        // Vérifie que le nouveau mot de passe correspond à la confirmation
        if (!nouveauMotDePasse.equals(confirmerMotDePasse)) {
            JOptionPane.showMessageDialog(this, "Le nouveau mot de passe ne correspond pas à la confirmation !");
            return;
        }

        // Connexion à la base et vérification de l'ancien mot de passe
        try (Connection conn = DBConnexion.getConnection();
             PreparedStatement stmt = conn.prepareStatement("SELECT mot_de_passe FROM utilisateurs WHERE email = ?")) {
            stmt.setString(1, txtEmailpro.getText());
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    String motDePasseStocke = rs.getString("mot_de_passe");

                    // Hash l'ancien mot de passe
                    String hashedAncienMotDePasse = hashPassword(ancienMotDePasse);
                   
                    // Vérifie les deux mots de passe hashés
                    if (!hashedAncienMotDePasse.equals(motDePasseStocke)) {
                        JOptionPane.showMessageDialog(this, "L'ancien mot de passe est incorrect !");
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Utilisateur introuvable !");
                    return;
                }
            }
        }

        // Mise à jour du mot de passe
        try (Connection conn = DBConnexion.getConnection();
             PreparedStatement stmt = conn.prepareStatement("UPDATE utilisateurs SET mot_de_passe = ? WHERE email = ?")) {
            String hashedNouveauMotDePasse = hashPassword(nouveauMotDePasse);
            stmt.setString(1, hashedNouveauMotDePasse);
            stmt.setString(2, txtEmailpro.getText());
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Mot de passe changé avec succès !");
                // Réinitialise les champs
                txtAncienMotDePasse.setText("");
                txtNouveauMotDePasse.setText("");
                txtConfirmmerMotDePasse.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la mise à jour du mot de passe !");
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors du traitement !");
    }



     

    }//GEN-LAST:event_btnChangerMotDePasseActionPerformed

    private void btnRetourAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourAccueilActionPerformed
        // TODO add your handling code here:
        AccueilUser accueil = new AccueilUser(txtNompro.getText(), txtPrenompro.getText(), txtEmailpro.getText());
accueil.setVisible(true);
this.dispose();
 
    }//GEN-LAST:event_btnRetourAccueilActionPerformed

    private void txtAncienMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAncienMotDePasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAncienMotDePasseActionPerformed

    private void txtEmailproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailproActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangerMotDePasse;
    private javax.swing.JButton btnRetourAccueil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel profil;
    private javax.swing.JPasswordField txtAncienMotDePasse;
    private javax.swing.JPasswordField txtConfirmmerMotDePasse;
    private javax.swing.JTextField txtEmailpro;
    private javax.swing.JTextField txtNompro;
    private javax.swing.JPasswordField txtNouveauMotDePasse;
    private javax.swing.JTextField txtPrenompro;
    // End of variables declaration//GEN-END:variables
}
