/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package biblio;
import javax.swing.*;
import biblio.Accueil;
import biblio.Rechercher;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import java.sql.*;


/**
 *
 * @author CLOVIS
 */

public class Rechercher extends javax.swing.JInternalFrame {
    
    
    
    
     private static PreferenceFrame instance;

    public static PreferenceFrame getInstance() {
        if (instance == null) {
            instance = new PreferenceFrame();
        }
        return instance;
    }

    public Rechercher() {
        super("Rechercher un livre", true, true, true, true); // Résizable, closable, etc.
        initComponents(); // Initialise les éléments visuels
        
                  ThemeManager.appliquerTheme(this.getContentPane());

        // Pour actualiser automatiquement quand on tape dans les champs
txtTitre.getDocument().addDocumentListener(new DocumentListener() {
    public void insertUpdate(DocumentEvent e) { rechercherLivreAuto(); }
    public void removeUpdate(DocumentEvent e) { rechercherLivreAuto(); }
    public void changedUpdate(DocumentEvent e) { rechercherLivreAuto(); }
});

txtAuteur.getDocument().addDocumentListener(new DocumentListener() {
    public void insertUpdate(DocumentEvent e) { rechercherLivreAuto(); }
    public void removeUpdate(DocumentEvent e) { rechercherLivreAuto(); }
    public void changedUpdate(DocumentEvent e) { rechercherLivreAuto(); }
});

    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titrerech = new javax.swing.JCheckBox();
        auteurrech = new javax.swing.JCheckBox();
        txtTitre = new javax.swing.JTextField();
        txtAuteur = new javax.swing.JTextField();
        btnRechercher = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResultats = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 102));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Rechercher un livre");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titrerech.setText("Titre");
        titrerech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/titre.png"))); // NOI18N

        auteurrech.setText("Auteur");
        auteurrech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/auteur.png"))); // NOI18N

        btnRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/recherch.png"))); // NOI18N
        btnRechercher.setText("Rechercher");
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titrerech)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(auteurrech)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAuteur)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titrerech)
                    .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(auteurrech)
                            .addComponent(txtAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRechercher)
                        .addGap(26, 26, 26))))
        );

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 181, 54));
        jLabel1.setText("Bienvenue dans la Zone de Recherche");

        tableResultats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableResultats.setToolTipText("");
        jScrollPane1.setViewportView(tableResultats);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        // TODO add your handling code here:
        
        String titre = txtTitre.getText().trim();
    String auteur = txtAuteur.getText().trim();

    try (Connection conn = DBConnexion.getConnection();
         PreparedStatement stmt = conn.prepareStatement(
             "SELECT * FROM livres WHERE titre LIKE ? AND auteur LIKE ?")) {

        stmt.setString(1, "%" + titre + "%");
        stmt.setString(2, "%" + auteur + "%");

        ResultSet rs = stmt.executeQuery();

        // Crée un modèle pour afficher les résultats
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID", "Titre", "Auteur", "Année", "Genre"}, 0
        );

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_livre"),
                rs.getString("titre"),
                rs.getString("auteur"),
                rs.getInt("AnneePublication"),
                rs.getString("genre")
            });
        }

        tableResultats.setModel(model); // Affiche dans la JTable

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors de la recherche : " + ex.getMessage());
    }
    
    
    }//GEN-LAST:event_btnRechercherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox auteurrech;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableResultats;
    private javax.swing.JCheckBox titrerech;
    private javax.swing.JTextField txtAuteur;
    private javax.swing.JTextField txtTitre;
    // End of variables declaration//GEN-END:variables

private void rechercherLivreAuto() {
    String titre = txtTitre.getText().trim();
    String auteur = txtAuteur.getText().trim();

    DefaultTableModel model = new DefaultTableModel(
        new String[]{"ID", "Titre", "Auteur", "Année", "Genre"}, 0
    );

    try (Connection conn = DBConnexion.getConnection();
         PreparedStatement stmt = conn.prepareStatement(
            "SELECT * FROM livres WHERE titre LIKE ? AND auteur LIKE ?"
         )) {

        stmt.setString(1, "%" + titre + "%");
        stmt.setString(2, "%" + auteur + "%");

        ResultSet rs = stmt.executeQuery();
        while (rs.next()) {
            int id = rs.getInt("id_livre");
            String t = rs.getString("titre");
            String a = rs.getString("auteur");
            int annee = rs.getInt("AnneePublication");
            String genre = rs.getString("genre");

            model.addRow(new Object[]{id, t, a, annee, genre});
        }

        tableResultats.setModel(model);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erreur de recherche : " + e.getMessage());
    }
}

}
